# Compose file for AMD GPU

services:
 portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
    volumes:
      - "./portainerdata:/data"
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  comfyui:
    init: true
    container_name: comfyui-rocm
    build:
      context: .
      dockerfile: Dockerfile
    image: "sudhyk/rocmdocker"
    ports:
      - "8188:8188"
    volumes:
      - "./storage:/root"
    environment:
      - CLI_ARGS=--use-pytorch-cross-attention
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    ipc: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - label:disable
    restart: unless-stopped
